#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');

// Read version from package.json
const pkg = JSON.parse(readFileSync(join(rootDir, 'package.json'), 'utf-8'));
const version = pkg.version;

// Generate version.ts for browser
const versionTs = `// Auto-generated by scripts/generate-version.js
export const VERSION = '${version}';
`;

writeFileSync(join(rootDir, 'mcp-client', 'version.ts'), versionTs);
console.log(`Generated version.ts with version ${version}`);
